#!/bin/bash

rm -r ../build
mkdir ../build
cd ../build
cmake -DCMAKE_TOOLCHAIN_FILE=../cross_compile/toolchain_win64.cmake ..
make
cp crazyforest.exe ../../crazyforest64.exe	
cd ../cross_compile

rm -r ../build
mkdir ../build
cd ../build
cmake -DCMAKE_TOOLCHAIN_FILE=../cross_compile/toolchain_win32.cmake ..
make
cp crazyforest.exe ../../crazyforest32.exe	
cd ../cross_compile

